import type { IdolData } from "~/helpers/idol.ts";

export const idol3: IdolData[] = [
	{
		Name: "Abyssal",
		Code: "MapRelicAbyssAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicAdditionalAbyssChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain an Abyss",
	},
	{
		Name: "Abyssal",
		Code: "MapRelicAbyssIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicIncreasedAbyssChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain an Abyss",
	},
	{
		Name: "of the Abyss",
		Code: "MapRelicAbyssIncreasedSpireChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicIncreasedAbyssSpireChance"],
		DropChance: 800,
		str: "Abysses in your Maps that do not lead to an Abyssal Depths have <span class='mod-value'>(40&ndash;60)</span>% increased chance to lead to a Stygian Spire",
	},
	{
		Name: "of the Abyss",
		Code: "MapRelicAbyssIncreasedDepthsChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicIncreasedAbyssDepthsChance"],
		DropChance: 800,
		str: "Abysses in your Maps have <span class='mod-value'>(40&ndash;60)</span>% increased chance to lead to an Abyssal Depths",
	},
	{
		Name: "of the Abyss",
		Code: "MapRelicAbyssPathSpawnAtLeastMagicChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicAbyssPathSpawnAtLeastMagicChance"],
		DropChance: 200,
		str: "Abyss Cracks in your Maps have <span class='mod-value'>(10&ndash;20)</span>% chance to spawn all Monsters as at least Magic",
	},
	{
		Name: "of the Abyss",
		Code: "MapRelicAbyssChasmSpawnAtLeastMagicChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicAbyssChasmSpawnAtLeastMagicChance"],
		DropChance: 200,
		str: "Abyss Pits in your Maps have <span class='mod-value'>(10&ndash;20)</span>% chance to spawn all Monsters as at least Magic",
	},
	{
		Name: "of Incursion",
		Code: "MapRelicIncursionAdditionalUpgradeNonResident1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicIncursionAdditionalUpgradeNonResident"],
		DropChance: 1500,
		str: "Killing non-resident Architects in your Maps has <span class='mod-value'>(30&ndash;50)</span>% chance to add<br/>an additional Upgrade Tier to the surviving Architect's Room",
	},
	{
		Name: "Alva's",
		Code: "MapRelicAdditionalIncursionChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicAdditionalIncursionChance"],
		DropChance: 1500,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain Alva",
	},
	{
		Name: "Alva's",
		Code: "MapRelicIncreasedIncursionChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicIncreasedIncursionChance"],
		DropChance: 1500,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain Alva",
	},
	{
		Name: "of Exiles",
		Code: "MapRelicAnarchyPossessed1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicAnarchyPossessed"],
		DropChance: 1000,
		str: "Wild Rogue Exiles in your Maps have <span class='mod-value'>(75&ndash;100)</span>% chance to be Possessed by a Tormented Spirit",
	},
	{
		Name: "Exiled",
		Code: "MapRelicAnarchyAdditionalExilesChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicAnarchyAdditionalExilesChance"],
		DropChance: 1000,
		str: "Your Maps have a <span class='mod-value'>(40&ndash;60)</span>% chance to contain an additional Rogue Exile",
	},
	{
		Name: "Exiled",
		Code: "MapRelicAnarchyExileChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicAnarchyExileChance"],
		DropChance: 1000,
		str: "Your Maps have <span class='mod-value'>+(15&ndash;25)</span>% chance to contain a Rogue Exile",
	},
	{
		Name: "of Beasts",
		Code: "MapRelicBestiaryAdditionalYellowBeasts1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBestiaryAdditionalYellowBeasts"],
		DropChance: 800,
		str: "Your Maps that contain capturable Beasts contain <span class='mod-value'>(3&ndash;4)</span> additional Yellow Beasts",
	},
	{
		Name: "Bestial",
		Code: "MapRelicBestiaryAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBestiaryAdditionalChance"],
		DropChance: 1500,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain Einhar",
	},
	{
		Name: "Bestial",
		Code: "MapRelicBestiaryIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBestiaryIncreasedChance"],
		DropChance: 1500,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain Einhar",
	},
	{
		Name: "of Beasts",
		Code: "MapRelicBestiaryChanceToNotConsumeBeast1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBestiaryChanceToNotConsumeBeast"],
		DropChance: 400,
		str: "Red Beasts captured in your Maps have a <span class='mod-value'>(40&ndash;60)</span>% chance to gain a Modifier that provides a chance to not to be consumed when sacrificed at the Blood Altar",
	},
	{
		Name: "of Beasts",
		Code: "MapRelicBestiaryRedBeastPairsChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBestiaryRedBeastPairsChance"],
		DropChance: 300,
		str: "Red Beasts in your Maps have <span class='mod-value'>(16&ndash;24)</span>% chance to appear in Pairs",
	},
	{
		Name: "Demonic",
		Code: "MapRelicBeyondAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBeyondAdditionalChance"],
		DropChance: 1000,
		str: "<span class='mod-value'>(40&ndash;60)</span>% chance for your Maps to attract Beyond Demons",
	},
	{
		Name: "of the Scourge",
		Code: "MapRelicBeyondIncreasedMonsterExperience1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBeyondIncreasedMonsterExperience"],
		DropChance: 250,
		str: "Beyond Demons in your Maps grant <span class='mod-value'>(20&ndash;30)</span>% increased Experience",
	},
	{
		Name: "of the Scourge",
		Code: "MapRelicBeyondIncreasedBossSpawnChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBeyondIncreasedBossSpawnChance"],
		DropChance: 300,
		str: "Beyond Portals in your Maps have <span class='mod-value'>(25&ndash;35)</span>% increased chance to spawn a Unique Boss",
	},
	{
		Name: "of the Scourge",
		Code: "MapRelicBeyondMoreDemonFactionDivinationCardQuantity1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBeyondMoreDemonFactionDivinationCardQuantity"],
		DropChance: 150,
		str: "<span class='mod-value'>(20&ndash;25)</span>% more Divination Cards found from Beyond Demons in your Maps<br/>that are followers of K'Tash",
	},
	{
		Name: "of the Scourge",
		Code: "MapRelicBeyondMorePaleFactionCurrencyQuantity1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBeyondMorePaleFactionCurrencyQuantity"],
		DropChance: 150,
		str: "<span class='mod-value'>(20&ndash;25)</span>% more Basic Currency Items found from Beyond Demons in your Maps<br/>that are followers of Beidat",
	},
	{
		Name: "of the Scourge",
		Code: "MapRelicBeyondMoreFleshFactionUniqueQuantity1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBeyondMoreFleshFactionUniqueQuantity"],
		DropChance: 150,
		str: "<span class='mod-value'>(20&ndash;25)</span>% more Unique Items found from Beyond Demons in your Maps<br/>that are followers of Ghorr",
	},
	{
		Name: "Blighted",
		Code: "MapRelicBlightAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBlightAdditionalEncounterChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain a Blight Encounter",
	},
	{
		Name: "Blighted",
		Code: "MapRelicBlightIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBlightAdditionalChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain a Blight Encounter",
	},
	{
		Name: "of Blight",
		Code: "MapRelicBlightMorePackSize1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBlightMorePackSize"],
		DropChance: 700,
		str: "Blight Encounters in your Maps spawn <span class='mod-value'>(25&ndash;35)</span>% more Non-Unique Monsters",
	},
	{
		Name: "of Blight",
		Code: "MapRelicBlightOilHigherTierChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBlightOilHigherTierChance"],
		DropChance: 600,
		str: "Oils found in your Maps have <span class='mod-value'>(20&ndash;25)</span>% chance to be 1 tier higher",
	},
	{
		Name: "of Blight",
		Code: "MapRelicBlightMonstersTakeIncreasedDamage1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBlightMonstersTakeIncreasedDamage"],
		DropChance: 700,
		str: "Blight Monsters in your Maps take <span class='mod-value'>(30&ndash;40)</span>% increased Damage",
	},
	{
		Name: "Breachlord's",
		Code: "MapRelicBreachAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBreachAdditionalChance"],
		DropChance: 1200,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain Breaches",
	},
	{
		Name: "Breachlord's",
		Code: "MapRelicBreachIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBreachIncreasedChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain a Breach",
	},
	{
		Name: "of the Breach",
		Code: "MapRelicBreachBossChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBreachBossChance"],
		DropChance: 400,
		str: "Breaches in your Maps have <span class='mod-value'>(35&ndash;45)</span>% increased chance to contain a Boss",
	},
	{
		Name: "of the Breach",
		Code: "MapRelicBreachBossFlawlessBreachstoneChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBreachBossFlawlessBreachstoneChance"],
		DropChance: 200,
		str: "Breachstones dropped by Breach Bosses in your Maps have <span class='mod-value'>(3&ndash;5)</span>% chance to be Flawless",
	},
	{
		Name: "of the Breach",
		Code: "MapRelicBreachIncreasdSpeed1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBreachSpeed"],
		DropChance: 400,
		str: "Breaches in your Maps open and close <span class='mod-value'>(6&ndash;10)</span>% faster",
	},
	{
		Name: "of the Breach",
		Code: "MapRelicBreachReducedSpeed1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBreachSpeed"],
		DropChance: 400,
		str: "Breaches in your Maps open and close <span class='mod-value'>(20&ndash;30)</span>% slower",
	},
	{
		Name: "Breachlord's",
		Code: "MapRelicBreachThreeAdditionalBreachChance1",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBreachThreeAdditionalBreachChance"],
		DropChance: 800,
		str: "Your Maps which contain Breaches have <span class='mod-value'>(5&ndash;10)</span>% chance to contain three additional Breaches",
	},
	{
		Name: "of the Breach",
		Code: "MapRelicBreachSuperChestSpawnChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBreachSuperChestSpawnChance"],
		DropChance: 300,
		str: "Breaches in your Maps have <span class='mod-value'>(10&ndash;15)</span>% chance to contain a Hand of Xesht-Ula",
	},
	{
		Name: "of the Breach",
		Code: "MapRelicBreachMonsterDensity1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBreachMonsterDensity"],
		DropChance: 300,
		str: "Breaches in your Maps have <span class='mod-value'>(8&ndash;12)</span>% increased Monster density",
	},
	{
		Name: "of the Exarch",
		Code: "MapRelicCleansingFireAltarSpawnChanceOnInfluenceAppearance1",
		Level: "73",
		ModGenerationTypeID: "2",
		ModFamilyList: [
			"MapRelicCleansingFireAltarSpawnChanceOnInfluenceAppearance",
		],
		DropChance: 1000,
		str: "<span class='mod-value'>(40&ndash;60)</span>% chance to spawn a Searing Exarch Altar when the Influence of The Searing Exarch first appears in your Maps",
	},
	{
		Name: "Delirious",
		Code: "MapRelicDeliriumAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicDeliriumAdditionalChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain a Mirror of Delirium",
	},
	{
		Name: "Delirious",
		Code: "MapRelicDeliriumIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicDeliriumIncreasedChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain a Mirror of Delirium",
	},
	{
		Name: "of Delirium",
		Code: "MapRelicDeliriumFasterDepthIncrease1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicDeliriumFasterDepthIncrease"],
		DropChance: 800,
		str: "Delirium in your Maps increases <span class='mod-value'>(35&ndash;50)</span>% faster with distance from the mirror",
	},
	{
		Name: "of Delirium",
		Code: "MapRelicDeliriumSecondaryWaveDelay1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicDeliriumSecondaryWaveDelay"],
		DropChance: 800,
		str: "Delirium Fog in your Maps lasts <span class='mod-value'>(10&ndash;15)</span> additional seconds before dissipating",
	},
	{
		Name: "of Delirium",
		Code: "MapRelicDeliriumAdditionalDeliriumOrbChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicDeliriumAdditionalDeliriumOrbChance"],
		DropChance: 400,
		str: "Delirium Rewards in your Maps have <span class='mod-value'>(8&ndash;12)</span>% increased chance to give Delirium Orbs",
	},
	{
		Name: "Niko's",
		Code: "MapRelicDelveAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicDelveAdditionalChance"],
		DropChance: 1500,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain Niko",
	},
	{
		Name: "Niko's",
		Code: "MapRelicDelveIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicDelveIncreasedChance"],
		DropChance: 1500,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain Niko",
	},
	{
		Name: "of the Underground",
		Code: "MapRelicDelveDoubleSulphiteChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicDelveDoubleSulphiteChance"],
		DropChance: 500,
		str: "Voltaxic Sulphite Veins and Chests in your Maps have <span class='mod-value'>(4&ndash;6)</span>% chance to contain double Sulphite",
	},
	{
		Name: "of the Underground",
		Code: "MapRelicDelveDamagerPerSulphiteMined1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicDelveDamagerPerSulphiteMined"],
		DropChance: 1000,
		str: "You Gain <span class='mod-value'>(30&ndash;40)</span>% increased Damage per stack of Sulphite Intoxication.",
	},
	{
		Name: "Domination",
		Code: "MapRelicShrineNumLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicShrineNum"],
		DropChance: 1000,
		str: "Your Maps contain an additional Shrine",
	},
	{
		Name: "Domination",
		Code: "MapRelicShrineIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicShrineIncreasedChance"],
		DropChance: 1000,
		str: "Your Maps have <span class='mod-value'>+(15&ndash;25)</span>% chance to contain a Shrine",
	},
	{
		Name: "of Domination",
		Code: "MapRelicShrineAdditionalPackChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicShrineAdditionalPackChance"],
		DropChance: 1000,
		str: "Shrines in your Maps have <span class='mod-value'>(40&ndash;60)</span>% chance to be guarded by an additional Pack of Monsters",
	},
	{
		Name: "of the Shaper",
		Code: "MapRelicShaperInfluencePackSize1",
		Level: "78",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicShaperInfluencePackSize"],
		DropChance: 475,
		str: "Monster Packs Influenced by The Shaper in your Maps have <span class='mod-value'>(15&ndash;25)</span>% increased Pack Size",
	},
	{
		Name: "of the Elder",
		Code: "MapRelicElderInfluencePackSize1",
		Level: "78",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicElderInfluencePackSize"],
		DropChance: 475,
		str: "Monster Packs Influenced by The Elder in your Maps have <span class='mod-value'>(15&ndash;25)</span>% increased Pack Size",
	},
	{
		Name: "Essence",
		Code: "MapRelicEssenceAdditionalMonolithsLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicEssenceAdditionalMonoliths"],
		DropChance: 1000,
		str: "Your Maps contain an additional Imprisoned Monster",
	},
	{
		Name: "Essence",
		Code: "MapRelicEssenceIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicEssenceIncreasedChance"],
		DropChance: 1000,
		str: "Your Maps have <span class='mod-value'>+(15&ndash;25)</span>% chance to contain an Imprisoned Monster",
	},
	{
		Name: "of Essences",
		Code: "MapRelicEssenceThreeAdditionalEssenceChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicEssenceThreeAdditionalEssenceChance"],
		DropChance: 1000,
		str: "Imprisoned Monsters in your Maps have <span class='mod-value'>(12&ndash;17)</span>% chance to have 3 additional Essences",
	},
	{
		Name: "Ruinic",
		Code: "MapRelicExpeditionAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicExpeditionAdditionalChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain an Expedition Encounter",
	},
	{
		Name: "Ruinic",
		Code: "MapRelicExpeditionIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicExpeditionIncreasedChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain an Expedition Encounter",
	},
	{
		Name: "of Expedition",
		Code: "MapRelicExpeditionExtraRelicSuffixChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicExpeditionExtraRelicSuffixChance"],
		DropChance: 400,
		str: "Remnants in your Maps have <span class='mod-value'>(25&ndash;35)</span>% chance to have an additional Suffix Modifier",
	},
	{
		Name: "of Expedition",
		Code: "MapRelicExpeditionTujenChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicExpeditionTujenChance"],
		DropChance: 250,
		str: "Expeditions in your Maps have <span class='mod-value'>(80&ndash;100)</span>% increased chance to be led by Tujen",
	},
	{
		Name: "of Expedition",
		Code: "MapRelicExpeditionDannigChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicExpeditionDannigChance"],
		DropChance: 250,
		str: "Expeditions in your Maps have <span class='mod-value'>(50&ndash;60)</span>% increased chance to be led by Dannig",
	},
	{
		Name: "of Expedition",
		Code: "MapRelicExpeditionMonstersSpawnMissingPercentLife1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicExpeditionMonstersSpawnMissingPercentLife"],
		DropChance: 600,
		str: "Expedition Monsters in your Maps spawn with an additional <span class='mod-value'>(6&ndash;10)</span>% of Life missing",
	},
	{
		Name: "of Expedition",
		Code: "MapRelicExpeditionRogChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicExpeditionRogChance"],
		DropChance: 250,
		str: "Expeditions in your Maps have <span class='mod-value'>(80&ndash;100)</span>% increased chance to be led by Rog",
	},
	{
		Name: "of Expedition",
		Code: "MapRelicExpeditionGwennenChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicExpeditionGwennenChance"],
		DropChance: 250,
		str: "Expeditions in your Maps have <span class='mod-value'>(80&ndash;100)</span>% increased chance to be led by Gwennen",
	},
	{
		Name: "Harbinger's",
		Code: "MapRelicHarbingerExtraHarbingersLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicHarbingerExtraHarbingers"],
		DropChance: 1000,
		str: "Your Maps contain an additional Harbinger",
	},
	{
		Name: "Harbinger's",
		Code: "MapRelicHarbingerAdditionalHarbingerChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicHarbingerAdditionalHarbingerChance"],
		DropChance: 1000,
		str: "Your Maps have a <span class='mod-value'>(15&ndash;25)</span>% chance to contain an additional Harbinger",
	},
	{
		Name: "of the Harbinger",
		Code: "MapRelicHarbingerPowerfulChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicHarbingerPowerfulChance"],
		DropChance: 1000,
		str: "Harbingers in your Maps have <span class='mod-value'>(20&ndash;25)</span>% chance to be replaced by a powerful Harbinger boss",
	},
	{
		Name: "Bountiful",
		Code: "MapRelicHarvestAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicHarvestAdditionalChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain The Sacred Grove",
	},
	{
		Name: "Bountiful",
		Code: "MapRelicHarvestIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicHarvestIncreasedChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain The Sacred Grove",
	},
	{
		Name: "of Harvest",
		Code: "MapRelicHarvestIncreasedLifeforceDropped1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicHarvestIncreasedLifeforceDropped"],
		DropChance: 700,
		str: "Harvest Monsters in your Maps drop <span class='mod-value'>(12&ndash;18)</span>% increased Quantity of Lifeforce",
	},
	{
		Name: "of Harvest",
		Code: "MapRelicHarvestOtherPlotNotWhitherChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicHarvestOtherPlotNotWhitherChance"],
		DropChance: 600,
		str: "Harvests in your Maps have <span class='mod-value'>(8&ndash;12)</span>% chance for the unchosen Crop to not wilt",
	},
	{
		Name: "of Harvest",
		Code: "MapRelicHarvestAdditionalPlotChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicHarvestAdditionalPlotChance"],
		DropChance: 700,
		str: "The Sacred Grove in your Maps has <span class='mod-value'>(40&ndash;60)</span>% chance to contain an additional Harvest",
	},
	{
		Name: "Smuggler's",
		Code: "MapRelicHeistAdditionalCacheChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicHeistAdditionalCacheChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain a Smuggler's Cache",
	},
	{
		Name: "Smuggler's",
		Code: "MapRelicHeistIncreasedCacheChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicHeistIncreasedCacheChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain a Smuggler's Cache",
	},
	{
		Name: "of Smuggling",
		Code: "MapRelicHeistCacheIncreasedContractDropChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicHeistCacheIncreasedContractDropChance"],
		DropChance: 1000,
		str: "Smuggler's Caches in your Maps have <span class='mod-value'>(40&ndash;60)</span>% increased chance to drop Contracts",
	},
	{
		Name: "of Smuggling",
		Code: "MapRelicHeistCacheMoreRogueMarkersPerOpenedCache1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicHeistCacheMoreRogueMarkersPerOpenedCache"],
		DropChance: 1000,
		str: "Smuggler's Caches drop <span class='mod-value'>(8&ndash;12)</span>% more Rogue Markers for each Smuggler's Cache opened in the Area",
	},
	{
		Name: "of Smuggling",
		Code: "MapRelicHeistHighValueContractChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicHeistHighValueContractChance"],
		DropChance: 500,
		str: "Heist Contracts found in your Maps are <span class='mod-value'>(70&ndash;90)</span>% more likely to target High Value Targets",
	},
	{
		Name: "of Smuggling",
		Code: "MapRelicHeistPreciousValueContractChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicHeistPreciousValueContractChance"],
		DropChance: 500,
		str: "Heist Contracts found in your Maps are <span class='mod-value'>(45&ndash;65)</span>% more likely to target Precious Targets",
	},
	{
		Name: "of Betrayal",
		Code: "MapRelicBetrayalReinforcementChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBetrayalReinforcementChance"],
		DropChance: 500,
		str: "Immortal Syndicate Members in your Maps have <span class='mod-value'>(20&ndash;25)</span>% increased chance to be accompanied by reinforcements",
	},
	{
		Name: "Syndicate's",
		Code: "MapRelicBetrayalAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBetrayalAdditionalChance"],
		DropChance: 1500,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain Jun",
	},
	{
		Name: "Syndicate's",
		Code: "MapRelicBetrayalIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicBetrayalIncreasedChance"],
		DropChance: 1500,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain Jun",
	},
	{
		Name: "of Betrayal",
		Code: "MapRelicBetrayalTargetsDropAdditionalVeiledItemChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBetrayalTargetsDropAdditionalVeiledItemChance"],
		DropChance: 500,
		str: "Immortal Syndicate Members in your Maps have <span class='mod-value'>(40&ndash;60)</span>% chance to drop an additional Veiled Item",
	},
	{
		Name: "of Betrayal",
		Code: "MapRelicBetrayalTargetItemRarity1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicBetrayalTargetItemRarity"],
		DropChance: 500,
		str: "<span class='mod-value'>(40&ndash;60)</span>% increased Rarity of Items Dropped by Immortal Syndicate Members in your Maps",
	},
	{
		Name: "Ascendant's",
		Code: "MapRelicAscendancyAdditionalTrialChance1",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicAscendancyAdditionalTrialChance"],
		DropChance: 1000,
		str: "Your Maps have <span class='mod-value'>+(8&ndash;12)</span>% chance to contain a Trial of Ascendancy",
	},
	{
		Name: "General's",
		Code: "MapRelicLegionAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicLegionAdditionalChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain a Legion Encounter",
	},
	{
		Name: "General's",
		Code: "MapRelicLegionIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicLegionIncreasedChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain a Legion Encounter",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionKaruiChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionKaruiChance"],
		DropChance: 200,
		str: "Legion Encounters in your Maps have <span class='mod-value'>(100&ndash;150)</span>% increased chance to include a Karui army",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionEternalEmpireChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionEternalEmpireChance"],
		DropChance: 200,
		str: "Legion Encounters in your Maps have <span class='mod-value'>(100&ndash;150)</span>% increased chance to include an Eternal Empire army",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionVaalChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionVaalChance"],
		DropChance: 200,
		str: "Legion Encounters in your Maps have <span class='mod-value'>(80&ndash;120)</span>% increased chance to include a Vaal army",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionTemplarChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionTemplarChance"],
		DropChance: 200,
		str: "Legion Encounters in your Maps have <span class='mod-value'>(75&ndash;100)</span>% increased chance to include a Templar army",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionMarakethChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionMarakethChance"],
		DropChance: 200,
		str: "Legion Encounters in your Maps have <span class='mod-value'>(60&ndash;80)</span>% increased chance to include a Maraketh army",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionSplinterDupeChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionSplinterDupeChance"],
		DropChance: 200,
		str: "Splinters dropped by Legion Monsters or contained in Legion Chests in your Maps have <span class='mod-value'>(15&ndash;20)</span>% chance to be Duplicated",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionChestSplinterDupeChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionChestSplinterDupeChance"],
		DropChance: 300,
		str: "Splinters contained in Legion Chests in your Maps have <span class='mod-value'>(20&ndash;25)</span>% chance to be Duplicated",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionMonsterSplinterDupeChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionMonsterSplinterDupeChance"],
		DropChance: 300,
		str: "Splinters dropped by Legion Monsters in your Maps have <span class='mod-value'>(20&ndash;25)</span>% chance to be Duplicated",
	},
	{
		Name: "of the Legion",
		Code: "MapRelicLegionMonsterWithRewardAdditionalRewardChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicLegionMonsterWithRewardAdditionalRewardChance"],
		DropChance: 200,
		str: "Legion Monsters in your Maps which have Rewards have <span class='mod-value'>(8&ndash;12)</span>% chance to gain two additional Rewards, and if not have <span class='mod-value'>(15&ndash;20)</span>% chance to gain one additional Reward",
	},
	{
		Name: "Cartographer's",
		Code: "MapRelicMapBossAdditionalAdjacentMapChance1",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicMapBossAdditionalAdjacentMapChance"],
		DropChance: 1000,
		str: "Final Map Boss in each Map has <span class='mod-value'>(4&ndash;6)</span>% chance to drop an additional connected Map",
	},
	{
		Name: "of the Bold",
		Code: "MapRelicFortuneFavoursTheBravePackSize1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicFortuneFavoursTheBravePackSize"],
		DropChance: 400,
		str: "<span class='mod-value'>(5&ndash;10)</span>% increased Pack Size of your Maps affected by Fortune Favours the Brave",
	},
	{
		Name: "of the Bold",
		Code: "MapRelicFortuneFavoursTheBraveItemQuantity1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicFortuneFavoursTheBraveItemQuantity"],
		DropChance: 400,
		str: "<span class='mod-value'>(5&ndash;10)</span>% increased Quantity of Items found in your Maps affected by Fortune Favours the Brave",
	},
	{
		Name: "of the Bold",
		Code: "MapRelicFortuneFavoursTheBraveItemRarity1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicFortuneFavoursTheBraveItemRarity"],
		DropChance: 400,
		str: "<span class='mod-value'>(10&ndash;20)</span>% increased Rarity of Items found in your Maps affected by Fortune Favours the Brave",
	},
	{
		Name: "Trialmaster's",
		Code: "MapRelicUltimatumIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicUltimatumIncreasedChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain an Ultimatum Encounter",
	},
	{
		Name: "Trialmaster's",
		Code: "MapRelicUltimatumAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicUltimatumAdditionalChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain an Ultimatum Encounter",
	},
	{
		Name: "of Ultimatum",
		Code: "MapRelicUltimatumIncreasedNumberOfMonsters1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicUltimatumIncreasedNumberOfMonsters"],
		DropChance: 600,
		str: "Ultimatum Encounters in your Maps spawn <span class='mod-value'>(15&ndash;20)</span>% increased number of Monsters",
	},
	{
		Name: "of Ultimatum",
		Code: "MapRelicUltimatumExperience1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicUltimatumExperience"],
		DropChance: 500,
		str: "Ultimatum Monsters in your Maps grant <span class='mod-value'>(40&ndash;60)</span>% increased Experience",
	},
	{
		Name: "of Ultimatum",
		Code: "MapRelicUltimatumInscribedRewardUniqueItemChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicUltimatumInscribedRewardUniqueItemChance"],
		DropChance: 300,
		str: "Inscribed Ultimatums found in your Maps have <span class='mod-value'>(40&ndash;60)</span>% increased chance to reward Unique Items",
	},
	{
		Name: "of Ultimatum",
		Code: "MapRelicUltimatumInscribedRewardCurrencyChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicUltimatumInscribedRewardCurrencyChance"],
		DropChance: 300,
		str: "Inscribed Ultimatums found in your Maps have <span class='mod-value'>(40&ndash;60)</span>% increased chance to reward Currency Items",
	},
	{
		Name: "of Ultimatum",
		Code: "MapRelicUltimatumInscribedRewardDivinationCardChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicUltimatumInscribedRewardDivinationCardChance"],
		DropChance: 300,
		str: "Inscribed Ultimatums found in your Maps have <span class='mod-value'>(40&ndash;60)</span>% increased chance to reward Divination Cards",
	},
	{
		Name: "Ritualistic",
		Code: "MapRelicRitualAdditionalChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicRitualAdditionalChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>+(40&ndash;60)</span>% chance to contain Ritual Altars",
	},
	{
		Name: "Ritualistic",
		Code: "MapRelicRitualIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicRitualIncreasedChance"],
		DropChance: 2000,
		str: "Your Maps have <span class='mod-value'>(192&ndash;240)</span>% increased chance to contain Ritual Altars",
	},
	{
		Name: "of the Ritual",
		Code: "MapRelicRitualIncreasedTribute1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicRitualIncreasedTribute"],
		DropChance: 800,
		str: "Monsters Sacrificed at Ritual Altars in your Maps grant <span class='mod-value'>(20&ndash;25)</span>% increased Tribute",
	},
	{
		Name: "of the Ritual",
		Code: "MapRelicRitualMonsterSpawningSpeed1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicRitualMonsterSpawningSpeed"],
		DropChance: 800,
		str: "Ritual Altars in your Maps spawn Monsters <span class='mod-value'>(15&ndash;20)</span>% faster",
	},
	{
		Name: "of the Ritual",
		Code: "MapRelicRitualDeferredRewardsTributeCost1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicRitualDeferredRewardsTributeCost"],
		DropChance: 400,
		str: "Deferring Favours at Ritual Altars in your Maps costs <span class='mod-value'>(15&ndash;20)</span>% reduced Tribute",
	},
	{
		Name: "of Skittering",
		Code: "MapRelicScarabBossAdditionalDropChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicScarabBossAdditionalDropChance"],
		DropChance: 475,
		str: "Final Map Boss in each Map has <span class='mod-value'>(20&ndash;25)</span>% chance to drop an additional Scarab",
	},
	{
		Name: "of Skittering",
		Code: "MapRelicScarabRareMonsterDropChancePerModifier1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicScarabRareMonsterDropChancePerModifier"],
		DropChance: 475,
		str: "Rare Monsters in your Maps have <span class='mod-value'>(40&ndash;60)</span>% increased chance to drop Scarabs per Monster Modifier affecting them",
	},
	{
		Name: "Cartographer's",
		Code: "MapRelicMapNonUniqueModEffect1",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicMapNonUniqueModEffect"],
		DropChance: 1000,
		str: "<span class='mod-value'>(8&ndash;12)</span>% increased effect of Explicit Modifiers on your Maps",
	},
	{
		Name: "Trapped",
		Code: "MapRelicStrongboxAdditionalLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicStrongboxAdditional"],
		DropChance: 1000,
		str: "Your Maps contain an additional Strongbox",
	},
	{
		Name: "Trapped",
		Code: "MapRelicStrongboxIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicStrongboxIncreasedChance"],
		DropChance: 1000,
		str: "Your Maps have <span class='mod-value'>+(15&ndash;25)</span>% chance to contain a Strongbox",
	},
	{
		Name: "of Ambush",
		Code: "MapRelicStrongboxCurrencyDuped1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicStrongboxCurrencyDuped"],
		DropChance: 333,
		str: "Currency Items from Strongboxes in your Maps are Duplicated",
	},
	{
		Name: "of Ambush",
		Code: "MapRelicStrongboxMapsDuped1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicStrongboxMapsDuped"],
		DropChance: 333,
		str: "Maps from Strongboxes in your Maps are Duplicated",
	},
	{
		Name: "of Ambush",
		Code: "MapRelicStrongboxDivinationCardsDuped1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicStrongboxDivinationCardsDuped"],
		DropChance: 333,
		str: "Divination Cards from Strongboxes in your Maps are Duplicated",
	},
	{
		Name: "of Ambush",
		Code: "MapRelicStrongboxGemsDuped1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicStrongboxGemsDuped"],
		DropChance: 333,
		str: "Gems contained in Strongboxes in your Maps are Duplicated",
	},
	{
		Name: "of the Eater",
		Code: "MapRelicTangleMonstersDropAdditionalEaterOfWorldsItem1",
		Level: "73",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicTangleMonstersDropAdditionalEaterOfWorldsItem"],
		DropChance: 475,
		str: "Monsters Influenced by The Eater of Worlds in your Maps have <span class='mod-value'>(0.8&ndash;1.2)</span>% chance to drop an item with an Eater of Worlds Implicit Modifier",
	},
	{
		Name: "of the Eater",
		Code: "MapRelicTangleAltarSpawnChance1",
		Level: "73",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicTangleAltarSpawnChance"],
		DropChance: 475,
		str: "<span class='mod-value'>(15&ndash;20)</span>% increased chance to find Eater of Worlds Altars in your Maps",
	},
	{
		Name: "Tormented",
		Code: "MapRelicTormentIncreasedChanceLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicTormentIncreasedChance"],
		DropChance: 1000,
		str: "Your Maps have <span class='mod-value'>+(15&ndash;25)</span>% chance to be haunted by a Tormented Spirit",
	},
	{
		Name: "Tormented",
		Code: "MapRelicTormentRareMonstersPossessedChance1",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicTormentRareMonstersPossessedChance"],
		DropChance: 1000,
		str: "Up to <span class='mod-value'>5</span> Rare Monsters in each of your Maps are Possessed and their Minions are Touched",
	},
	{
		Name: "Tormented",
		Code: "MapRelicTormentExtraSpiritsLarge",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicTormentExtraSpirits"],
		DropChance: 1000,
		str: "Your Maps are haunted by an additional Tormented Spirit",
	},
	{
		Name: "of Corruption",
		Code: "MapRelicMapUniqueMonsterItemsDropCorruptedChance1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicMapUniqueMonsterItemsDropCorruptedChance"],
		DropChance: 475,
		str: "Items dropped by Unique Monsters have <span class='mod-value'>(10&ndash;15)</span>% chance to be Corrupted",
	},
	{
		Name: "of Corruption",
		Code: "MapRelicVaalSideAreaVaalVesselDuplicateRewards1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicVaalSideAreaVaalVesselDuplicateRewards"],
		DropChance: 475,
		str: "Vaal Side Areas in your Maps have <span class='mod-value'>(15&ndash;20)</span>% chance for Rewards from Vaal Vessels to be Duplicated",
	},
	{
		Name: "Kirac's",
		Code: "MapRelicMapAdditionalKiracMissionOnCompletionChance1",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicMapAdditionalKiracMissionOnCompletionChance"],
		DropChance: 1000,
		str: "Your Maps have <span class='mod-value'>(5&ndash;8)</span>% chance to grant an additional Kirac Mission on Completion",
	},
	{
		Name: "Kirac's",
		Code: "MapRelicMapAdditionakKiracMissionOnCompletionChancePerMyriad1",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: [
			"MapRelicMapAdditionakKiracMissionOnCompletionChancePerMyriad",
		],
		DropChance: 1000,
		str: "Your Maps have <span class='mod-value'>(2&ndash;2.5)</span>% chance to grant an additional Kirac Mission on Completion",
	},
	{
		Name: "Cartographer's",
		Code: "MapRelicIncreasedMapDropRarity1",
		Level: "68",
		ModGenerationTypeID: "2",
		ModFamilyList: ["MapRelicIncreasedMapDropRarity"],
		DropChance: 2000,
		str: "<span class='mod-value'>(25&ndash;35)</span>% increased Rarity of Maps found in your Maps",
	},
	{
		Name: "Cartographer's",
		Code: "MapRelicIncreasedItemRarity1",
		Level: "68",
		ModGenerationTypeID: "1",
		ModFamilyList: ["MapRelicIncreasedItemRarity"],
		DropChance: 1000,
		str: "<span class='mod-value'>(12&ndash;16)</span>% increased Rarity of Items found in your Maps",
	},
];
